site_name: Stable Baselines - Model Based Reinforcement Learning
theme:
  name: material
  features:
    - navigation.expand
plugins:
  - awesome-pages
  - search
  - with-pdf:
      author: 'LMU Munich'
      cover_subtitle: Documentation
      copyright: 'Apache 2.0 License'
      output_path: ./stable-baselines-model-based-rl-DOCS.pdf
      enabled_if_env: DOCS_PDF_EXPORT
nav:
  - index.md
  - 'Using the Framework':
    - sampling.md
    - dynamic-model-training.md
    - environment-wrapping.md
    - policy-training.md
  - configuration-file.md
  - ...
markdown_extensions:
  - pymdownx.critic
