###############SAMPLING###############
# CSV/Data Configuration
input_config:
    action_cols:
        - A_0
        - A_1
    action_type: DISCRETE  # one of: DISCRETE, MULTI_DISCRETE, BOX
    discrete_colum_sets: null
    box_bounds: null
    observation_cols:
        - X_0
        - X_1
        - X_2
        - X_3
    gym_environment_name: 'Cart_Pole_v1'
    input_file_name: 'train.csv'
####################################################

###############DYNAMIC MODEL###############
dynamic_model:
    training:
        train_test_ration: 0.7  # 0.7: 70% of the data is used for training, 30% for testing
        lag: 1
        validation_steps: 100
        validation_freq: 1
        max_epochs: 10 #100
        steps_per_epoch: 100
        learning_rate: 0.1
        loss: mse   # Mean squared error
        optimizer: adam
        batch_size: 32
        patience: 15    # Epochs in which no learning success is achieved, after which the training is discontinued
    model:  # Parameters of the model key must be left in this form for the tensorflow deserializer to work
        backend: tensorflow
        class_name: Sequential
        config:
            name: 'my_net'
            layers:
            - class_name: LSTM
              config:
                units: 4
            - class_name: Dense
              config:
                units: 4
                activation: relu

    utility_flags:
        log_training: True
        evaluate_model: True
        plot_results: True
        export_model: True
####################################################

###############CAPSULING###############
capsuling:
    reinforcement_learning_algorithm: 'PPO'
####################################################
