# CSV/Data Configuration
action_cols:
    - A_0
    - A_1
action_type: DISCRETE  # one of: DISCRETE, MULTI_DISCRETE, BOX
discrete_colum_sets: null
observation_cols:
    - X_0
    - X_1
    - X_2
    - X_3

reinforcement_learning_algorithm: 'PPO'
model_type: 'MLP'
gym_environment_name: 'Cart_Pole_v1'
input_file_name: 'train.csv'
train_test_ration: 0.2
lags: '3'
