# CSV/Data Configuration
action_cols:
    - A_0
    - A_1
action_type: DISCRETE  # one of: DISCRETE, MULTI_DISCRETE, BOX
discrete_colum_sets: null
observation_cols:
    - X_0
    - X_1
    - X_2
    - X_3
gym_environment_name: 'Cart_Pole_v1'
input_file_name: 'train.csv'

# Dynamic Model Configuration
model_type: 'MLP'
train_test_ration: 0.7
lags: '3'
max_epochs: 1000
steps_per_epoch: 100
validation_steps: 100
validation_freq: 1

# Capsulating Configuration
reinforcement_learning_algorithm: 'PPO'
