#
# Gym Sampling
#
gym_sampling:
    gym_environment_name: 'CartPole-v1'

#
# Input Data Configuration
#
input_config:
    action_cols:
        - A_0
        - A_1
    action_type: DISCRETE  # one of: DISCRETE, MULTI_DISCRETE, BOX
    discrete_colum_sets: null
    action_box_bounds:
        low: null
        high: null
    observation_cols:
        - X_0
        - X_1
        - X_2
        - X_3
    observation_bounds:
        low: null
        high: null
    input_file_name: 'train.csv'

#
# Dynamic Model
#
dynamic_model:
    training:
        train_test_ration: 0.7  # 0.7: 70% of the data is used for training, 30% for testing
        lag: 4
        validation_steps: 100
        validation_freq: 1
        max_epochs: 50
        steps_per_epoch: 1000
        learning_rate: 0.05
        optimizer: adam
        batch_size: 64
        patience: 15    # Epochs in which no learning success is achieved, after which the training is discontinued
    keras_model:  # Parameters of the model key must be left in this form for the tensorflow deserializer to work
        class_name: Sequential
        config:
            name: 'my_net'
            layers:
            - class_name: LSTM
              config:
                units: 50

    validation:
        noise:
            calc_mean: false
            std: 0.1
            percentage: 0.5

    utility_flags:
        log_training: True
        save: True
        evaluate_model: True
        plot_results: True
        export_model: True
        artificial_noise: False

#
# Model Wrapping
#
model_wrapping:
    reward:
        type: CONSTANT  # one of CONSTANT, EVAL, or HANDLER
        value: 1.0
    done:
        type: CONSTANT  # one of CONSTANT, EVAL, or HANDLER
        value: 200
    reset:
        type: RANDOM  # one of RANDOM, STATIC, EPISODE_START, or HANDLER
        value:
            buffer: null
            current_state: null
        data_file: null

#
# Stable Baselines Policy Configuration
#
sb_policy:
    reinforcement_learning_algorithm: 'PPO'
    policy: 'MlpPolicy'
    timesteps: 10000
